/**
 * Canonical icon map. Toda feature importa daqui — não direto de @phosphor-icons/react.
 * ADR-05 (Spec 09 §12). Permite swap futuro sem big-bang refactor.
 *
 * Re-exporting from `@phosphor-icons/react/dist/ssr` so Server Components can
 * render icons without forcing the entire CSR React-context module client-side.
 * Client Components still get fully interactive icons (size/weight/color).
 */

export {
  // navigation (inbox icon = Tray in Phosphor)
  Tray as Inbox,
  PlugsConnected,
  QrCode,
  Kanban,
  Users,
  UsersThree,
  Storefront,
  Robot,
  ShieldCheck,
  Gear,
  Wrench,
  Lightning,
  House,
  // admin platform
  Buildings,
  ChatsCircle,
  ClipboardText,
  Scales,
  Gauge,
  WifiSlash,
  Clock,
  // health dashboard
  WifiHigh,
  Brain,
  ArrowsClockwise,
  Dot,
  // actions
  PaperPlaneTilt,
  Check,
  Checks,
  X,
  Plus,
  Trash,
  FloppyDisk,
  PencilSimple,
  MagnifyingGlass,
  Pause,
  Play,
  Copy,
  Archive,
  // feedback
  CheckCircle,
  Warning,
  WarningOctagon,
  Info,
  CircleNotch,
  // lgpd
  Scales as ScalesSimple,
  Eye,
  ChartBar,
  ClockCountdown,
  // theme
  Sun,
  Moon,
  MonitorPlay,
  // conversation
  ChatCircle,
  Phone,
  Paperclip,
  Image as ImageIcon,
  MusicNote,
  FileText,
  Lock,
  Receipt,
  Wallet,
  Tag,
  Question,
  Keyboard,
  // super app 3D — novas abas
  Printer,
  Package,
  Drop,
  Cube,
  CalendarBlank,
  ShoppingCart,
  Sparkle,
  Handshake,
  Toolbox,
  Ruler,
  AddressBook,
  ChartLineUp,
  FolderOpen,
  Calculator,
  // sales shell (E1)
  Funnel,
  DownloadSimple,
  Table,
  Rows,
  BookmarkSimple,
  // misc
  DotsThree,
  CaretDown,
  CaretUp,
  CaretDoubleLeft,
  CaretDoubleRight,
  CaretLeft,
  CaretRight,
  ArrowRight,
  ArrowLeft,
  SignOut,
  Bell,
  TrendUp,
  Star,
  Globe,
  Coins,
  ArrowsDownUp,
} from "@phosphor-icons/react/dist/ssr";
