import type { PublicFilament } from './types';

export const FALLBACK_FILAMENTS: PublicFilament[] = [
  {
    id: 'fallback-pla-preto',
    slug: 'pla-premium-preto-profundo',
    name: 'PLA Premium Preto Profundo',
    description: 'Filamento de alta precisão com acabamento fosco suave e excelente adesão entre camadas.',
    priceCents: 11900,
    image: '/images/filaments/pla-black.jpg',
    images: ['/images/filaments/pla-black.jpg'],
    sortOrder: 1,
    materialId: 'mat-pla',
    materialName: 'PLA Premium',
    line: 'Pro Series',
    brand: 'GLTech3D Lab',
    colorName: 'Preto Profundo',
    colorHex: '#1A1A1A',
    diameterMm: 1.75,
    netWeightG: 1000,
    nozzleTempMin: 200,
    nozzleTempMax: 220,
    bedTempMin: 50,
    bedTempMax: 60,
    tdsUrl: null,
    availability: 'pronta_entrega',
    availabilityLabel: 'Pronta Entrega',
    orderable: true,
  },
  {
    id: 'fallback-pla-branco',
    slug: 'pla-premium-branco-neve',
    name: 'PLA Premium Branco Neve',
    description: 'Ideal para prototipagem visual e peças decorativas com brancura pura e tolerância dimensional de 0.02mm.',
    priceCents: 11900,
    image: '/images/filaments/pla-white.jpg',
    images: ['/images/filaments/pla-white.jpg'],
    sortOrder: 2,
    materialId: 'mat-pla',
    materialName: 'PLA Premium',
    line: 'Pro Series',
    brand: 'GLTech3D Lab',
    colorName: 'Branco Neve',
    colorHex: '#F8F9FA',
    diameterMm: 1.75,
    netWeightG: 1000,
    nozzleTempMin: 200,
    nozzleTempMax: 220,
    bedTempMin: 50,
    bedTempMax: 60,
    tdsUrl: null,
    availability: 'pronta_entrega',
    availabilityLabel: 'Pronta Entrega',
    orderable: true,
  },
  {
    id: 'fallback-pla-silk-bronze',
    slug: 'pla-silk-bronze-metalico',
    name: 'PLA Silk Bronze Metálico',
    description: 'Brilho acetinado luxuoso com partículas reflexivas. Excelente para troféus e estatuetas decorativas.',
    priceCents: 13900,
    image: '/images/filaments/pla-silk-bronze.jpg',
    images: ['/images/filaments/pla-silk-bronze.jpg'],
    sortOrder: 3,
    materialId: 'mat-silk',
    materialName: 'PLA Silk',
    line: 'Aesthetic Line',
    brand: 'GLTech3D Lab',
    colorName: 'Bronze Metálico',
    colorHex: '#A6815C',
    diameterMm: 1.75,
    netWeightG: 1000,
    nozzleTempMin: 205,
    nozzleTempMax: 225,
    bedTempMin: 55,
    bedTempMax: 65,
    tdsUrl: null,
    availability: 'pronta_entrega',
    availabilityLabel: 'Pronta Entrega',
    orderable: true,
  },
  {
    id: 'fallback-petg-cinza',
    slug: 'petg-tecnico-cinza-industrial',
    name: 'PETG Técnico Cinza Industrial',
    description: 'Alta resistência mecânica, térmica e química para peças funcionais, gabaritos e suportes de oficina.',
    priceCents: 12900,
    image: '/images/filaments/petg-grey.jpg',
    images: ['/images/filaments/petg-grey.jpg'],
    sortOrder: 4,
    materialId: 'mat-petg',
    materialName: 'PETG Técnico',
    line: 'Industrial Engineering',
    brand: 'GLTech3D Lab',
    colorName: 'Cinza Industrial',
    colorHex: '#5A6268',
    diameterMm: 1.75,
    netWeightG: 1000,
    nozzleTempMin: 230,
    nozzleTempMax: 250,
    bedTempMin: 70,
    bedTempMax: 85,
    tdsUrl: null,
    availability: 'pronta_entrega',
    availabilityLabel: 'Pronta Entrega',
    orderable: true,
  },
  {
    id: 'fallback-tpu-flex',
    slug: 'tpu-95a-preto-flexivel',
    name: 'TPU 95A Flexível Preto',
    description: 'Elastômero de alta flexibilidade, absorção de impactos e durabilidade para amortecedores e vedantes.',
    priceCents: 14900,
    image: '/images/filaments/tpu-black.jpg',
    images: ['/images/filaments/tpu-black.jpg'],
    sortOrder: 5,
    materialId: 'mat-tpu',
    materialName: 'TPU Flex',
    line: 'Flex Pro',
    brand: 'GLTech3D Lab',
    colorName: 'Preto Flex',
    colorHex: '#222222',
    diameterMm: 1.75,
    netWeightG: 1000,
    nozzleTempMin: 215,
    nozzleTempMax: 235,
    bedTempMin: 40,
    bedTempMax: 60,
    tdsUrl: null,
    availability: 'pronta_entrega',
    availabilityLabel: 'Pronta Entrega',
    orderable: true,
  },
  {
    id: 'fallback-pla-carbon',
    slug: 'pla-cf-fibra-de-carbono',
    name: 'PLA-CF Fibra de Carbono',
    description: 'Reforçado com fibras curtas de carbono para máxima rigidez estrutural, acabamento fosco e estabilidade dimensional.',
    priceCents: 16900,
    image: '/images/filaments/pla-cf.jpg',
    images: ['/images/filaments/pla-cf.jpg'],
    sortOrder: 6,
    materialId: 'mat-cf',
    materialName: 'PLA Carbon',
    line: 'Extreme Performance',
    brand: 'GLTech3D Lab',
    colorName: 'Grafite Carbono',
    colorHex: '#2E3440',
    diameterMm: 1.75,
    netWeightG: 1000,
    nozzleTempMin: 210,
    nozzleTempMax: 230,
    bedTempMin: 50,
    bedTempMax: 65,
    tdsUrl: null,
    availability: 'pronta_entrega',
    availabilityLabel: 'Pronta Entrega',
    orderable: true,
  },
];
