import type { PublicFilament } from './types';

export const FALLBACK_FILAMENTS: PublicFilament[] = [
  // ─── DESTAQUES ATIVOS (Mencionados em estoque imediato) ─────────────────────
  {
    id: 'pla-basic-vermelho',
    slug: 'pla-basic-vermelho-1kg',
    name: 'PLA Basic Vermelho',
    description: 'Filamento PLA Basic vermelho vivo com alta saturação, excelente adesão de mesa e enrolamento de precisão.',
    priceCents: 8900,
    image: '/images/Filamentos/PLA VERMELHO BASIC.jpg',
    images: ['/images/Filamentos/PLA VERMELHO BASIC.jpg'],
    sortOrder: 1,
    materialId: 'mat-pla-basic',
    materialName: 'PLA Basic',
    line: 'Standard',
    brand: 'GLTech3D',
    colorName: 'Vermelho',
    colorHex: '#D32F2F',
    diameterMm: 1.75,
    netWeightG: 1000,
    nozzleTempMin: 200,
    nozzleTempMax: 220,
    bedTempMin: 50,
    bedTempMax: 60,
    tdsUrl: null,
    availability: 'em_estoque',
    availabilityLabel: 'Em Estoque',
    orderable: true,
  },
  {
    id: 'pla-silk-cinza',
    slug: 'pla-silk-cinza-prata-1kg',
    name: 'PLA Silk Cinza Prata',
    description: 'Prata acetinado reluzente de brilho metálico contínuo, perfeito para peças e estatuetas decorativas.',
    priceCents: 9600,
    image: '/images/Filamentos/PLA SILK CINZA.jpg',
    images: ['/images/Filamentos/PLA SILK CINZA.jpg'],
    sortOrder: 2,
    materialId: 'mat-pla-silk',
    materialName: 'PLA Silk',
    line: 'Aesthetic Silk',
    brand: 'GLTech3D Lab',
    colorName: 'Silk Cinza',
    colorHex: '#A8A9AD',
    diameterMm: 1.75,
    netWeightG: 1000,
    nozzleTempMin: 205,
    nozzleTempMax: 225,
    bedTempMin: 55,
    bedTempMax: 65,
    tdsUrl: null,
    availability: 'em_estoque',
    availabilityLabel: 'Em Estoque',
    orderable: true,
  },
  {
    id: 'pla-premium-cinza',
    slug: 'pla-premium-cinza-espacial-1kg',
    name: 'PLA Premium Cinza Espacial',
    description: 'Pigmentação mineral selecionada para disfarçar camadas e valorizar relevos complexos com tolerância ±0.02mm.',
    priceCents: 9200,
    image: '/images/Filamentos/PLA PREMIUM CINZA.jpg',
    images: ['/images/Filamentos/PLA PREMIUM CINZA.jpg'],
    sortOrder: 3,
    materialId: 'mat-pla-premium',
    materialName: 'PLA Premium',
    line: 'Pro Series',
    brand: 'GLTech3D Lab',
    colorName: 'Cinza Espacial',
    colorHex: '#5A6268',
    diameterMm: 1.75,
    netWeightG: 1000,
    nozzleTempMin: 205,
    nozzleTempMax: 225,
    bedTempMin: 50,
    bedTempMax: 60,
    tdsUrl: null,
    availability: 'em_estoque',
    availabilityLabel: 'Em Estoque',
    orderable: true,
  },
  {
    id: 'pla-silk-dourado',
    slug: 'pla-silk-dourado-1kg',
    name: 'PLA Silk Dourado',
    description: 'Brilho acetinado luxuoso com reflexos metálicos intensos para troféus, adornos e bustos artísticos.',
    priceCents: 9600,
    image: '/images/Filamentos/PLA SILK DOURADO.jpg',
    images: ['/images/Filamentos/PLA SILK DOURADO.jpg'],
    sortOrder: 4,
    materialId: 'mat-pla-silk',
    materialName: 'PLA Silk',
    line: 'Aesthetic Silk',
    brand: 'GLTech3D Lab',
    colorName: 'Silk Dourado',
    colorHex: '#E5B80B',
    diameterMm: 1.75,
    netWeightG: 1000,
    nozzleTempMin: 205,
    nozzleTempMax: 225,
    bedTempMin: 55,
    bedTempMax: 65,
    tdsUrl: null,
    availability: 'em_estoque',
    availabilityLabel: 'Em Estoque',
    orderable: true,
  },
  {
    id: 'pla-basic-branco',
    slug: 'pla-basic-branco-1kg',
    name: 'PLA Basic Branco',
    description: 'Filamento PLA Basic de alta qualidade com brancura homogênea, alta fluidez e excelente custo-benefício.',
    priceCents: 8900,
    image: '/images/Filamentos/PLA BASIC BRANCO.jpg',
    images: ['/images/Filamentos/PLA BASIC BRANCO.jpg'],
    sortOrder: 5,
    materialId: 'mat-pla-basic',
    materialName: 'PLA Basic',
    line: 'Standard',
    brand: 'GLTech3D',
    colorName: 'Branco',
    colorHex: '#F8F9FA',
    diameterMm: 1.75,
    netWeightG: 1000,
    nozzleTempMin: 200,
    nozzleTempMax: 220,
    bedTempMin: 50,
    bedTempMax: 60,
    tdsUrl: null,
    availability: 'em_estoque',
    availabilityLabel: 'Em Estoque',
    orderable: true,
  },
  {
    id: 'pla-silk-preto',
    slug: 'pla-silk-preto-1kg',
    name: 'PLA Silk Preto',
    description: 'Preto seda brilhante com toque acetinado profundo e acabamento ultra refinado para peças premium.',
    priceCents: 9600,
    image: '',
    images: [],
    sortOrder: 6,
    materialId: 'mat-pla-silk',
    materialName: 'PLA Silk',
    line: 'Aesthetic Silk',
    brand: 'GLTech3D Lab',
    colorName: 'Silk Preto',
    colorHex: '#222226',
    diameterMm: 1.75,
    netWeightG: 1000,
    nozzleTempMin: 205,
    nozzleTempMax: 225,
    bedTempMin: 55,
    bedTempMax: 65,
    tdsUrl: null,
    availability: 'em_estoque',
    availabilityLabel: 'Em Estoque',
    orderable: true,
  },
  {
    id: 'pla-premium-vermelho',
    slug: 'pla-premium-vermelho-1kg',
    name: 'PLA Premium Vermelho',
    description: 'Vermelho vibrante de grau profissional com alta resistência mecânica e acabamento impecável.',
    priceCents: 9200,
    image: '',
    images: [],
    sortOrder: 7,
    materialId: 'mat-pla-premium',
    materialName: 'PLA Premium',
    line: 'Pro Series',
    brand: 'GLTech3D Lab',
    colorName: 'Vermelho',
    colorHex: '#C62828',
    diameterMm: 1.75,
    netWeightG: 1000,
    nozzleTempMin: 205,
    nozzleTempMax: 225,
    bedTempMin: 50,
    bedTempMax: 60,
    tdsUrl: null,
    availability: 'em_estoque',
    availabilityLabel: 'Em Estoque',
    orderable: true,
  },
  {
    id: 'pla-basic-dourado',
    slug: 'pla-basic-dourado-1kg',
    name: 'PLA Basic Dourado',
    description: 'Tom dourado clássico para impressões com ótimo acabamento e facilidade de impressão.',
    priceCents: 8900,
    image: '',
    images: [],
    sortOrder: 8,
    materialId: 'mat-pla-basic',
    materialName: 'PLA Basic',
    line: 'Standard',
    brand: 'GLTech3D',
    colorName: 'Dourado',
    colorHex: '#D4AF37',
    diameterMm: 1.75,
    netWeightG: 1000,
    nozzleTempMin: 200,
    nozzleTempMax: 220,
    bedTempMin: 50,
    bedTempMax: 60,
    tdsUrl: null,
    availability: 'em_estoque',
    availabilityLabel: 'Em Estoque',
    orderable: true,
  },

  // ─── PETG FOTOGRAFADOS (R$ 89,00) ──────────────────────────────────────────
  {
    id: 'petg-branco',
    slug: 'petg-branco-tecnico-1kg',
    name: 'PETG Branco Técnico',
    description: 'Resistência ao impacto, flexibilidade moderada e excelente estabilidade externa com acabamento branco liso.',
    priceCents: 8900,
    image: '/images/Filamentos/PETG BRANCO.jpg',
    images: ['/images/Filamentos/PETG BRANCO.jpg'],
    sortOrder: 9,
    materialId: 'mat-petg',
    materialName: 'PETG',
    line: 'Engineering',
    brand: '3D Fila',
    colorName: 'Branco',
    colorHex: '#F5F5F5',
    diameterMm: 1.75,
    netWeightG: 1000,
    nozzleTempMin: 230,
    nozzleTempMax: 250,
    bedTempMin: 70,
    bedTempMax: 85,
    tdsUrl: null,
    availability: 'em_estoque',
    availabilityLabel: 'Em Estoque',
    orderable: true,
  },
  {
    id: 'petg-preto',
    slug: 'petg-preto-tecnico-1kg',
    name: 'PETG Preto Técnico',
    description: 'Alta resistência mecânica, química e térmica para suportes, gabaritos e peças funcionais de engenharia.',
    priceCents: 8900,
    image: '/images/Filamentos/PETG PRETO.jpg',
    images: ['/images/Filamentos/PETG PRETO.jpg'],
    sortOrder: 10,
    materialId: 'mat-petg',
    materialName: 'PETG',
    line: 'Engineering',
    brand: '3D Fila',
    colorName: 'Preto',
    colorHex: '#1F2421',
    diameterMm: 1.75,
    netWeightG: 1000,
    nozzleTempMin: 230,
    nozzleTempMax: 250,
    bedTempMin: 70,
    bedTempMax: 85,
    tdsUrl: null,
    availability: 'em_estoque',
    availabilityLabel: 'Em Estoque',
    orderable: true,
  },
  {
    id: 'petg-cinza',
    slug: 'petg-cinza-industrial-1kg',
    name: 'PETG Cinza Industrial',
    description: 'Filamento PETG ideal para uso industrial, suportes veiculares e protótipos de engenharia.',
    priceCents: 8900,
    image: '',
    images: [],
    sortOrder: 11,
    materialId: 'mat-petg',
    materialName: 'PETG',
    line: 'Engineering',
    brand: 'GLTech3D Lab',
    colorName: 'Cinza Industrial',
    colorHex: '#606470',
    diameterMm: 1.75,
    netWeightG: 1000,
    nozzleTempMin: 230,
    nozzleTempMax: 250,
    bedTempMin: 70,
    bedTempMax: 85,
    tdsUrl: null,
    availability: 'em_estoque',
    availabilityLabel: 'Em Estoque',
    orderable: true,
  },
  {
    id: 'petg-azul',
    slug: 'petg-azul-oceano-1kg',
    name: 'PETG Azul Oceano',
    description: 'Resistência UV e excelente acabamento superficial em tom azul corporativo.',
    priceCents: 8900,
    image: '',
    images: [],
    sortOrder: 12,
    materialId: 'mat-petg',
    materialName: 'PETG',
    line: 'Engineering',
    brand: 'GLTech3D Lab',
    colorName: 'Azul',
    colorHex: '#1E3D59',
    diameterMm: 1.75,
    netWeightG: 1000,
    nozzleTempMin: 230,
    nozzleTempMax: 250,
    bedTempMin: 70,
    bedTempMax: 85,
    tdsUrl: null,
    availability: 'em_estoque',
    availabilityLabel: 'Em Estoque',
    orderable: true,
  },
  {
    id: 'petg-vermelho',
    slug: 'petg-vermelho-1kg',
    name: 'PETG Vermelho',
    description: 'Filamento PETG vermelho de alta resistência mecânica para peças que exigem durabilidade.',
    priceCents: 8900,
    image: '',
    images: [],
    sortOrder: 13,
    materialId: 'mat-petg',
    materialName: 'PETG',
    line: 'Engineering',
    brand: 'GLTech3D Lab',
    colorName: 'Vermelho',
    colorHex: '#990000',
    diameterMm: 1.75,
    netWeightG: 1000,
    nozzleTempMin: 230,
    nozzleTempMax: 250,
    bedTempMin: 70,
    bedTempMax: 85,
    tdsUrl: null,
    availability: 'em_estoque',
    availabilityLabel: 'Em Estoque',
    orderable: true,
  },
  {
    id: 'petg-cristal',
    slug: 'petg-cristal-translucido-1kg',
    name: 'PETG Cristal Translúcido',
    description: 'Translúcido cristal com transmissão de luz natural para cúpulas, difusores e visores.',
    priceCents: 8900,
    image: '',
    images: [],
    sortOrder: 14,
    materialId: 'mat-petg',
    materialName: 'PETG',
    line: 'Engineering',
    brand: 'GLTech3D Lab',
    colorName: 'Cristal',
    colorHex: '#E0E6ED',
    diameterMm: 1.75,
    netWeightG: 1000,
    nozzleTempMin: 230,
    nozzleTempMax: 250,
    bedTempMin: 70,
    bedTempMax: 85,
    tdsUrl: null,
    availability: 'em_estoque',
    availabilityLabel: 'Em Estoque',
    orderable: true,
  },

  // ─── DEMAIS PLA BASIC FOTOGRAFADOS (R$ 89,00) ──────────────────────────────
  {
    id: 'pla-basic-azul',
    slug: 'pla-basic-azul-1kg',
    name: 'PLA Basic Azul',
    description: 'Filamento PLA Basic azul royal vibrante com estabilidade dimensional comprovada.',
    priceCents: 8900,
    image: '/images/Filamentos/PLA BASIC AZUL.jpg',
    images: ['/images/Filamentos/PLA BASIC AZUL.jpg'],
    sortOrder: 15,
    materialId: 'mat-pla-basic',
    materialName: 'PLA Basic',
    line: 'Standard',
    brand: 'GLTech3D',
    colorName: 'Azul',
    colorHex: '#1976D2',
    diameterMm: 1.75,
    netWeightG: 1000,
    nozzleTempMin: 200,
    nozzleTempMax: 220,
    bedTempMin: 50,
    bedTempMax: 60,
    tdsUrl: null,
    availability: 'em_estoque',
    availabilityLabel: 'Em Estoque',
    orderable: true,
  },
  {
    id: 'pla-basic-amarelo',
    slug: 'pla-basic-amarelo-1kg',
    name: 'PLA Basic Amarelo',
    description: 'Filamento PLA Basic amarelo canário intenso com excelente fluidez.',
    priceCents: 8900,
    image: '/images/Filamentos/PLA BASIC AMARELO.jpg',
    images: ['/images/Filamentos/PLA BASIC AMARELO.jpg'],
    sortOrder: 16,
    materialId: 'mat-pla-basic',
    materialName: 'PLA Basic',
    line: 'Standard',
    brand: 'GLTech3D',
    colorName: 'Amarelo',
    colorHex: '#FBC02D',
    diameterMm: 1.75,
    netWeightG: 1000,
    nozzleTempMin: 200,
    nozzleTempMax: 220,
    bedTempMin: 50,
    bedTempMax: 60,
    tdsUrl: null,
    availability: 'em_estoque',
    availabilityLabel: 'Em Estoque',
    orderable: true,
  },

  // ─── DEMAIS PLA PREMIUM FOTOGRAFADOS (R$ 92,00) ─────────────────────────────
  {
    id: 'pla-premium-preto',
    slug: 'pla-premium-preto-profundo-1kg',
    name: 'PLA Premium Preto Profundo',
    description: 'PLA Premium de alta precisão com acabamento preto aveludado e tolerância de 0.02mm.',
    priceCents: 9200,
    image: '/images/Filamentos/PLA PREMIUM PRETO.jpg',
    images: ['/images/Filamentos/PLA PREMIUM PRETO.jpg'],
    sortOrder: 17,
    materialId: 'mat-pla-premium',
    materialName: 'PLA Premium',
    line: 'Pro Series',
    brand: 'GLTech3D Lab',
    colorName: 'Preto Profundo',
    colorHex: '#111111',
    diameterMm: 1.75,
    netWeightG: 1000,
    nozzleTempMin: 205,
    nozzleTempMax: 225,
    bedTempMin: 50,
    bedTempMax: 60,
    tdsUrl: null,
    availability: 'em_estoque',
    availabilityLabel: 'Em Estoque',
    orderable: true,
  },
  {
    id: 'pla-premium-dourado',
    slug: 'pla-premium-dourado-1kg',
    name: 'PLA Premium Dourado',
    description: 'Pigmentação dourada refinada com brilho contínuo e ótima rigidez estrutural.',
    priceCents: 9200,
    image: '/images/Filamentos/PLA PREMIUM DOURADO.jpg',
    images: ['/images/Filamentos/PLA PREMIUM DOURADO.jpg'],
    sortOrder: 18,
    materialId: 'mat-pla-premium',
    materialName: 'PLA Premium',
    line: 'Pro Series',
    brand: 'GLTech3D Lab',
    colorName: 'Dourado',
    colorHex: '#D4AF37',
    diameterMm: 1.75,
    netWeightG: 1000,
    nozzleTempMin: 205,
    nozzleTempMax: 225,
    bedTempMin: 50,
    bedTempMax: 60,
    tdsUrl: null,
    availability: 'em_estoque',
    availabilityLabel: 'Em Estoque',
    orderable: true,
  },
  {
    id: 'pla-premium-azul',
    slug: 'pla-premium-azul-1kg',
    name: 'PLA Premium Azul',
    description: 'Azul cobalto premium para impressões técnicas e estéticas de alto impacto.',
    priceCents: 9200,
    image: '/images/Filamentos/PLA PREMIUM AZUL.jpg',
    images: ['/images/Filamentos/PLA PREMIUM AZUL.jpg'],
    sortOrder: 19,
    materialId: 'mat-pla-premium',
    materialName: 'PLA Premium',
    line: 'Pro Series',
    brand: 'GLTech3D Lab',
    colorName: 'Azul',
    colorHex: '#1976D2',
    diameterMm: 1.75,
    netWeightG: 1000,
    nozzleTempMin: 205,
    nozzleTempMax: 225,
    bedTempMin: 50,
    bedTempMax: 60,
    tdsUrl: null,
    availability: 'em_estoque',
    availabilityLabel: 'Em Estoque',
    orderable: true,
  },
  {
    id: 'pla-premium-azul-claro',
    slug: 'pla-premium-azul-claro-1kg',
    name: 'PLA Premium Azul Claro',
    description: 'Tom azul bebê/pastel com acabamento suave e homogêneo.',
    priceCents: 9200,
    image: '/images/Filamentos/PLA PREMIUM AZUL CLARO.jpg',
    images: ['/images/Filamentos/PLA PREMIUM AZUL CLARO.jpg'],
    sortOrder: 20,
    materialId: 'mat-pla-premium',
    materialName: 'PLA Premium',
    line: 'Pro Series',
    brand: 'GLTech3D Lab',
    colorName: 'Azul Claro',
    colorHex: '#64B5F6',
    diameterMm: 1.75,
    netWeightG: 1000,
    nozzleTempMin: 205,
    nozzleTempMax: 225,
    bedTempMin: 50,
    bedTempMax: 60,
    tdsUrl: null,
    availability: 'em_estoque',
    availabilityLabel: 'Em Estoque',
    orderable: true,
  },
  {
    id: 'pla-premium-verde',
    slug: 'pla-premium-verde-1kg',
    name: 'PLA Premium Verde',
    description: 'Verde vivo com saturação equilibrada e fidelidade dimensional.',
    priceCents: 9200,
    image: '/images/Filamentos/PLA PREMIUM VERDE.jpg',
    images: ['/images/Filamentos/PLA PREMIUM VERDE.jpg'],
    sortOrder: 21,
    materialId: 'mat-pla-premium',
    materialName: 'PLA Premium',
    line: 'Pro Series',
    brand: 'GLTech3D Lab',
    colorName: 'Verde',
    colorHex: '#2E7D32',
    diameterMm: 1.75,
    netWeightG: 1000,
    nozzleTempMin: 205,
    nozzleTempMax: 225,
    bedTempMin: 50,
    bedTempMax: 60,
    tdsUrl: null,
    availability: 'em_estoque',
    availabilityLabel: 'Em Estoque',
    orderable: true,
  },
  {
    id: 'pla-premium-verde-musgo',
    slug: 'pla-premium-verde-musgo-1kg',
    name: 'PLA Premium Verde Musgo',
    description: 'Verde musgo oliva selecionado para miniaturas táticas e dioramas.',
    priceCents: 9200,
    image: '/images/Filamentos/PLA PREMIUM VERDE MUSGO.jpg',
    images: ['/images/Filamentos/PLA PREMIUM VERDE MUSGO.jpg'],
    sortOrder: 22,
    materialId: 'mat-pla-premium',
    materialName: 'PLA Premium',
    line: 'Pro Series',
    brand: 'GLTech3D Lab',
    colorName: 'Verde Musgo',
    colorHex: '#556B2F',
    diameterMm: 1.75,
    netWeightG: 1000,
    nozzleTempMin: 205,
    nozzleTempMax: 225,
    bedTempMin: 50,
    bedTempMax: 60,
    tdsUrl: null,
    availability: 'em_estoque',
    availabilityLabel: 'Em Estoque',
    orderable: true,
  },
  {
    id: 'pla-premium-marrom',
    slug: 'pla-premium-marrom-1kg',
    name: 'PLA Premium Marrom',
    description: 'Marrom chocolate terroso com textura superficial macia e limpa.',
    priceCents: 9200,
    image: '/images/Filamentos/PLA PREMIUM MARROM.jpg',
    images: ['/images/Filamentos/PLA PREMIUM MARROM.jpg'],
    sortOrder: 23,
    materialId: 'mat-pla-premium',
    materialName: 'PLA Premium',
    line: 'Pro Series',
    brand: 'GLTech3D Lab',
    colorName: 'Marrom',
    colorHex: '#5D4037',
    diameterMm: 1.75,
    netWeightG: 1000,
    nozzleTempMin: 205,
    nozzleTempMax: 225,
    bedTempMin: 50,
    bedTempMax: 60,
    tdsUrl: null,
    availability: 'em_estoque',
    availabilityLabel: 'Em Estoque',
    orderable: true,
  },
  {
    id: 'pla-premium-bege',
    slug: 'pla-premium-bege-1kg',
    name: 'PLA Premium Bege',
    description: 'Tom bege neutro elegante, perfeito para maquetes e acabamentos arquitetônicos.',
    priceCents: 9200,
    image: '/images/Filamentos/PLA PREMIUM BEGE.jpg',
    images: ['/images/Filamentos/PLA PREMIUM BEGE.jpg'],
    sortOrder: 24,
    materialId: 'mat-pla-premium',
    materialName: 'PLA Premium',
    line: 'Pro Series',
    brand: 'GLTech3D Lab',
    colorName: 'Bege',
    colorHex: '#D7CCC8',
    diameterMm: 1.75,
    netWeightG: 1000,
    nozzleTempMin: 205,
    nozzleTempMax: 225,
    bedTempMin: 50,
    bedTempMax: 60,
    tdsUrl: null,
    availability: 'em_estoque',
    availabilityLabel: 'Em Estoque',
    orderable: true,
  },
  {
    id: 'pla-premium-skin',
    slug: 'pla-premium-skin-1kg',
    name: 'PLA Premium Skin',
    description: 'Tom pele/nude desenvolvido especificamente para action figures realistas e bustos.',
    priceCents: 9200,
    image: '/images/Filamentos/PLA PREMIUM SKIN.jpg',
    images: ['/images/Filamentos/PLA PREMIUM SKIN.jpg'],
    sortOrder: 25,
    materialId: 'mat-pla-premium',
    materialName: 'PLA Premium',
    line: 'Pro Series',
    brand: 'GLTech3D Lab',
    colorName: 'Cor Skin',
    colorHex: '#E8BEAC',
    diameterMm: 1.75,
    netWeightG: 1000,
    nozzleTempMin: 205,
    nozzleTempMax: 225,
    bedTempMin: 50,
    bedTempMax: 60,
    tdsUrl: null,
    availability: 'em_estoque',
    availabilityLabel: 'Em Estoque',
    orderable: true,
  },
  {
    id: 'pla-premium-rosa',
    slug: 'pla-premium-rosa-1kg',
    name: 'PLA Premium Rosa',
    description: 'Rosa chiclete elegante de cor sólida e acabamento sedoso.',
    priceCents: 9200,
    image: '/images/Filamentos/PLA PREMIUM ROSA.jpg',
    images: ['/images/Filamentos/PLA PREMIUM ROSA.jpg'],
    sortOrder: 26,
    materialId: 'mat-pla-premium',
    materialName: 'PLA Premium',
    line: 'Pro Series',
    brand: 'GLTech3D Lab',
    colorName: 'Rosa',
    colorHex: '#E91E63',
    diameterMm: 1.75,
    netWeightG: 1000,
    nozzleTempMin: 205,
    nozzleTempMax: 225,
    bedTempMin: 50,
    bedTempMax: 60,
    tdsUrl: null,
    availability: 'em_estoque',
    availabilityLabel: 'Em Estoque',
    orderable: true,
  },
  {
    id: 'pla-premium-roxo',
    slug: 'pla-premium-roxo-1kg',
    name: 'PLA Premium Roxo',
    description: 'Roxo nobre de alta cobertura e excelente coesão entre camadas.',
    priceCents: 9200,
    image: '/images/Filamentos/PLA PREMIUM ROXO.jpg',
    images: ['/images/Filamentos/PLA PREMIUM ROXO.jpg'],
    sortOrder: 27,
    materialId: 'mat-pla-premium',
    materialName: 'PLA Premium',
    line: 'Pro Series',
    brand: 'GLTech3D Lab',
    colorName: 'Roxo',
    colorHex: '#7B1FA2',
    diameterMm: 1.75,
    netWeightG: 1000,
    nozzleTempMin: 205,
    nozzleTempMax: 225,
    bedTempMin: 50,
    bedTempMax: 60,
    tdsUrl: null,
    availability: 'em_estoque',
    availabilityLabel: 'Em Estoque',
    orderable: true,
  },
  {
    id: 'pla-premium-lilas',
    slug: 'pla-premium-lilas-1kg',
    name: 'PLA Premium Lilás',
    description: 'Tom lilás delicado com pigmentação homogênea.',
    priceCents: 9200,
    image: '/images/Filamentos/PLA PREMIUM LILAS.jpg',
    images: ['/images/Filamentos/PLA PREMIUM LILAS.jpg'],
    sortOrder: 28,
    materialId: 'mat-pla-premium',
    materialName: 'PLA Premium',
    line: 'Pro Series',
    brand: 'GLTech3D Lab',
    colorName: 'Lilás',
    colorHex: '#BA68C8',
    diameterMm: 1.75,
    netWeightG: 1000,
    nozzleTempMin: 205,
    nozzleTempMax: 225,
    bedTempMin: 50,
    bedTempMax: 60,
    tdsUrl: null,
    availability: 'em_estoque',
    availabilityLabel: 'Em Estoque',
    orderable: true,
  },
  {
    id: 'pla-premium-marmore',
    slug: 'pla-premium-marmore-1kg',
    name: 'PLA Premium Mármore',
    description: 'Efeito mármore com micropartículas escuras que imitam rocha natural e mascaram completamente as linhas de camada.',
    priceCents: 9200,
    image: '/images/Filamentos/PLA PREMIUM MARMORE.jpg',
    images: ['/images/Filamentos/PLA PREMIUM MARMORE.jpg'],
    sortOrder: 29,
    materialId: 'mat-pla-premium',
    materialName: 'PLA Premium',
    line: 'Pro Series',
    brand: 'GLTech3D Lab',
    colorName: 'Mármore',
    colorHex: '#ECEFF1',
    diameterMm: 1.75,
    netWeightG: 1000,
    nozzleTempMin: 205,
    nozzleTempMax: 225,
    bedTempMin: 50,
    bedTempMax: 60,
    tdsUrl: null,
    availability: 'em_estoque',
    availabilityLabel: 'Em Estoque',
    orderable: true,
  },
  {
    id: 'pla-premium-amarelo',
    slug: 'pla-premium-amarelo-1kg',
    name: 'PLA Premium Amarelo',
    description: 'Amarelo sol intenso de grau técnico e ótima resistência à tração.',
    priceCents: 9200,
    image: '/images/Filamentos/PLA PREMIUM AMARELO.jpg',
    images: ['/images/Filamentos/PLA PREMIUM AMARELO.jpg'],
    sortOrder: 30,
    materialId: 'mat-pla-premium',
    materialName: 'PLA Premium',
    line: 'Pro Series',
    brand: 'GLTech3D Lab',
    colorName: 'Amarelo',
    colorHex: '#FBC02D',
    diameterMm: 1.75,
    netWeightG: 1000,
    nozzleTempMin: 205,
    nozzleTempMax: 225,
    bedTempMin: 50,
    bedTempMax: 60,
    tdsUrl: null,
    availability: 'em_estoque',
    availabilityLabel: 'Em Estoque',
    orderable: true,
  },

  // ─── DEMAIS PLA SILK FOTOGRAFADOS (R$ 96,00) ───────────────────────────────
  {
    id: 'pla-silk-roxo',
    slug: 'pla-silk-roxo-ametista-1kg',
    name: 'PLA Silk Roxo Ametista',
    description: 'Roxo ametista reluzente com brilho acetinado vívido e aspecto cerâmico de alto luxo.',
    priceCents: 9600,
    image: '/images/Filamentos/PLA SILK ROXO.jpg',
    images: ['/images/Filamentos/PLA SILK ROXO.jpg'],
    sortOrder: 31,
    materialId: 'mat-pla-silk',
    materialName: 'PLA Silk',
    line: 'Aesthetic Silk',
    brand: 'GLTech3D Lab',
    colorName: 'Silk Roxo',
    colorHex: '#8E24AA',
    diameterMm: 1.75,
    netWeightG: 1000,
    nozzleTempMin: 205,
    nozzleTempMax: 225,
    bedTempMin: 55,
    bedTempMax: 65,
    tdsUrl: null,
    availability: 'em_estoque',
    availabilityLabel: 'Em Estoque',
    orderable: true,
  },
  {
    id: 'pla-silk-rosa',
    slug: 'pla-silk-rosa-1kg',
    name: 'PLA Silk Rosa',
    description: 'Rosa acetinado com acabamento sedoso perolado.',
    priceCents: 9600,
    image: '/images/Filamentos/PLA ROSA SILK.jpg',
    images: ['/images/Filamentos/PLA ROSA SILK.jpg'],
    sortOrder: 32,
    materialId: 'mat-pla-silk',
    materialName: 'PLA Silk',
    line: 'Aesthetic Silk',
    brand: 'GLTech3D Lab',
    colorName: 'Silk Rosa',
    colorHex: '#F06292',
    diameterMm: 1.75,
    netWeightG: 1000,
    nozzleTempMin: 205,
    nozzleTempMax: 225,
    bedTempMin: 55,
    bedTempMax: 65,
    tdsUrl: null,
    availability: 'em_estoque',
    availabilityLabel: 'Em Estoque',
    orderable: true,
  },
  {
    id: 'pla-silk-cobre',
    slug: 'pla-silk-cobre-metalico-1kg',
    name: 'PLA Silk Cobre Metálico',
    description: 'Tom cobre metálico brilhante para peças decorativas e troféus.',
    priceCents: 9600,
    image: '/images/Filamentos/PLA SILK COBRE.jpg',
    images: ['/images/Filamentos/PLA SILK COBRE.jpg'],
    sortOrder: 33,
    materialId: 'mat-pla-silk',
    materialName: 'PLA Silk',
    line: 'Aesthetic Silk',
    brand: 'GLTech3D Lab',
    colorName: 'Silk Cobre',
    colorHex: '#B87333',
    diameterMm: 1.75,
    netWeightG: 1000,
    nozzleTempMin: 205,
    nozzleTempMax: 225,
    bedTempMin: 55,
    bedTempMax: 65,
    tdsUrl: null,
    availability: 'em_estoque',
    availabilityLabel: 'Em Estoque',
    orderable: true,
  },
  {
    id: 'pla-silk-branco',
    slug: 'pla-silk-branco-1kg',
    name: 'PLA Silk Branco Perolado',
    description: 'Branco perolado com reflexos cintilantes sedosos de alta elegância.',
    priceCents: 9600,
    image: '',
    images: [],
    sortOrder: 34,
    materialId: 'mat-pla-silk',
    materialName: 'PLA Silk',
    line: 'Aesthetic Silk',
    brand: 'GLTech3D Lab',
    colorName: 'Silk Branco',
    colorHex: '#F0F3F4',
    diameterMm: 1.75,
    netWeightG: 1000,
    nozzleTempMin: 205,
    nozzleTempMax: 225,
    bedTempMin: 55,
    bedTempMax: 65,
    tdsUrl: null,
    availability: 'em_estoque',
    availabilityLabel: 'Em Estoque',
    orderable: true,
  },
  {
    id: 'pla-silk-vermelho',
    slug: 'pla-silk-vermelho-rubi-1kg',
    name: 'PLA Silk Vermelho Rubi',
    description: 'Vermelho rubi com brilho acetinado vívido e reflexo metálico.',
    priceCents: 9600,
    image: '',
    images: [],
    sortOrder: 35,
    materialId: 'mat-pla-silk',
    materialName: 'PLA Silk',
    line: 'Aesthetic Silk',
    brand: 'GLTech3D Lab',
    colorName: 'Silk Vermelho',
    colorHex: '#C2185B',
    diameterMm: 1.75,
    netWeightG: 1000,
    nozzleTempMin: 205,
    nozzleTempMax: 225,
    bedTempMin: 55,
    bedTempMax: 65,
    tdsUrl: null,
    availability: 'em_estoque',
    availabilityLabel: 'Em Estoque',
    orderable: true,
  },

  // ─── PLA GENERIC (R$ 84,00) ────────────────────────────────────────────────
  {
    id: 'pla-generic-preto',
    slug: 'pla-generic-preto-1kg',
    name: 'PLA Generic Preto',
    description: 'Filamento PLA Generic com o melhor custo-benefício para impressões diárias e lotes.',
    priceCents: 8400,
    image: '',
    images: [],
    sortOrder: 36,
    materialId: 'mat-pla-generic',
    materialName: 'PLA Generic',
    line: 'Economy',
    brand: 'Generic',
    colorName: 'Preto',
    colorHex: '#1A1A1A',
    diameterMm: 1.75,
    netWeightG: 1000,
    nozzleTempMin: 195,
    nozzleTempMax: 215,
    bedTempMin: 50,
    bedTempMax: 60,
    tdsUrl: null,
    availability: 'em_estoque',
    availabilityLabel: 'Em Estoque',
    orderable: true,
  },
  {
    id: 'pla-generic-branco',
    slug: 'pla-generic-branco-1kg',
    name: 'PLA Generic Branco',
    description: 'Filamento PLA Generic branco com excelente fluidez e custo reduzido.',
    priceCents: 8400,
    image: '',
    images: [],
    sortOrder: 37,
    materialId: 'mat-pla-generic',
    materialName: 'PLA Generic',
    line: 'Economy',
    brand: 'Generic',
    colorName: 'Branco',
    colorHex: '#F8F9FA',
    diameterMm: 1.75,
    netWeightG: 1000,
    nozzleTempMin: 195,
    nozzleTempMax: 215,
    bedTempMin: 50,
    bedTempMax: 60,
    tdsUrl: null,
    availability: 'em_estoque',
    availabilityLabel: 'Em Estoque',
    orderable: true,
  },
  {
    id: 'pla-generic-cinza',
    slug: 'pla-generic-cinza-1kg',
    name: 'PLA Generic Cinza',
    description: 'Filamento PLA Generic cinza para prototipagem rápida e testes funcionais.',
    priceCents: 8400,
    image: '',
    images: [],
    sortOrder: 38,
    materialId: 'mat-pla-generic',
    materialName: 'PLA Generic',
    line: 'Economy',
    brand: 'Generic',
    colorName: 'Cinza',
    colorHex: '#757575',
    diameterMm: 1.75,
    netWeightG: 1000,
    nozzleTempMin: 195,
    nozzleTempMax: 215,
    bedTempMin: 50,
    bedTempMax: 60,
    tdsUrl: null,
    availability: 'em_estoque',
    availabilityLabel: 'Em Estoque',
    orderable: true,
  },
  {
    id: 'pla-generic-azul',
    slug: 'pla-generic-azul-1kg',
    name: 'PLA Generic Azul',
    description: 'Filamento PLA Generic azul royal econômico e confiável.',
    priceCents: 8400,
    image: '',
    images: [],
    sortOrder: 39,
    materialId: 'mat-pla-generic',
    materialName: 'PLA Generic',
    line: 'Economy',
    brand: 'Generic',
    colorName: 'Azul',
    colorHex: '#1976D2',
    diameterMm: 1.75,
    netWeightG: 1000,
    nozzleTempMin: 195,
    nozzleTempMax: 215,
    bedTempMin: 50,
    bedTempMax: 60,
    tdsUrl: null,
    availability: 'em_estoque',
    availabilityLabel: 'Em Estoque',
    orderable: true,
  },
];
