/**
 * Verify-then-publish of a file uploaded to the private `orcamentos` bucket
 * (used by POST /api/v1/public/orcamento/upload-slot/confirm).
 *
 * Pendência 19 ("troca do arquivo depois da confirmação"): it is not confirmed
 * whether Storage honours `x-upsert` on an upload through a signed token. If it
 * does, the uploader could replace the object AFTER the content check and keep
 * a 7-day link to whatever they put there. Closed here by ordering:
 *
 *   1. COPY the uploaded object to `verified/<same path>` — a prefix no upload
 *      slot can target (slot paths are generated by the server and always
 *      start with a timestamp).
 *   2. Delete the original, so nothing at the upload path keeps a link.
 *   3. Run the content check on the COPY (head bytes; for .3mf also the ZIP
 *      central directory) — the bytes checked are the bytes that will be served.
 *   4. Sign the COPY.
 *
 * Any non-success outcome after the copy (rejected content, unreadable bytes,
 * signing failure) deletes the verified copy. A retry of the same slot finds
 * the copy already there and checks it AGAIN before signing.
 *
 * Storage and HTTP are injected so the ordering is unit-tested without I/O.
 */
import {
  SNIFF_BYTES,
  ZIP_TAIL_BYTES,
  check3mfPackage,
  checkOrcamentoFile,
  readHead,
  totalSizeFromHeaders,
} from "@/lib/orcamento/file-check";
import type { OrcamentoKind } from "@/lib/schemas/orcamento-upload";
import { logger } from "@/lib/logger";

export const VERIFIED_PREFIX = "verified/";

export function verifiedPathOf(path: string): string {
  return `${VERIFIED_PREFIX}${path}`;
}

type StorageErr = { message: string } | null;

/** The subset of the supabase-js bucket API used here. */
export interface OrcamentoBucket {
  copy(fromPath: string, toPath: string): Promise<{ error: StorageErr }>;
  remove(paths: string[]): Promise<{ error: StorageErr }>;
  createSignedUrl(
    path: string,
    expiresIn: number,
  ): Promise<{ data: { signedUrl: string } | null; error: StorageErr }>;
}

export type FetchFn = (url: string, init: { headers: Record<string, string>; cache: "no-store" }) => Promise<Response>;

export type VerifyUploadResult =
  | { ok: true; verifiedPath: string; signedUrl: string; originalRemoveError?: string | null }
  | {
      ok: false;
      status: 404 | 422 | 500 | 502;
      code: "not_found" | "file_rejected" | "internal_error";
      /** Internal reason, for logs only. */
      reason: string;
    };

export interface VerifyUploadArgs {
  bucket: OrcamentoBucket;
  path: string;
  kind: OrcamentoKind;
  linkTtlSeconds: number;
  fetchFn?: FetchFn;
  /** Validity of the internal links used only to read bytes. */
  sniffTtlSeconds?: number;
}

const notFound = (reason: string): VerifyUploadResult => ({ ok: false, status: 404, code: "not_found", reason });

async function readBytes(
  fetchFn: FetchFn,
  url: string,
  range: string,
  max: number,
): Promise<{ ok: true; bytes: Uint8Array; status: number; headers: Headers } | { ok: false; status: number; reason: string }> {
  let res: Response;
  try {
    res = await fetchFn(url, { headers: { Range: range }, cache: "no-store" });
  } catch (err) {
    return { ok: false, status: 502, reason: err instanceof Error ? err.message : String(err) };
  }
  if (res.status !== 200 && res.status !== 206) {
    await res.body?.cancel();
    return { ok: false, status: res.status === 404 || res.status === 400 ? 404 : 502, reason: `HTTP ${res.status}` };
  }
  return { ok: true, bytes: await readHead(res.body, max), status: res.status, headers: res.headers };
}

export async function verifyAndPublishUpload(args: VerifyUploadArgs): Promise<VerifyUploadResult> {
  const { bucket, path } = args;
  const fetchFn: FetchFn = args.fetchFn ?? ((url, init) => fetch(url, init));
  const sniffTtl = args.sniffTtlSeconds ?? 60;
  const verifiedPath = verifiedPathOf(path);

  // 1. Copy. "Already exists" = a previous confirm of this same slot (retry
  //    after a network error, or a second call): the existing copy is checked
  //    AGAIN below — never signed on trust.
  const { error: copyErr } = await bucket.copy(path, verifiedPath);
  if (copyErr && !/exist/i.test(copyErr.message)) {
    // Storage answers "Object not found" when nothing was uploaded.
    if (/not.?found/i.test(copyErr.message)) return notFound(copyErr.message);
    return { ok: false, status: 500, code: "internal_error", reason: `copy: ${copyErr.message}` };
  }

  // 2. Nothing stays at the upload path (best effort: the copy is what counts;
  //    on a retry the original is usually gone already).
  const { error: removeOrigErr } = await bucket.remove([path]);

  // From here on, ANY outcome other than success deletes the verified copy, so
  // a rejected or half-checked file is never left where a link could reach it.
  let published = false;
  try {
    const result = await checkAndSign(args, fetchFn, sniffTtl, verifiedPath);
    if (result.ok) {
      published = true;
      return { ...result, originalRemoveError: copyErr ? null : (removeOrigErr?.message ?? null) };
    }
    return result;
  } finally {
    if (!published) {
      const { error: cleanupErr } = await bucket.remove([verifiedPath]);
      if (cleanupErr) {
        logger.warn("orcamento_verified_copy_cleanup_failed", { path: verifiedPath, details: cleanupErr.message });
      }
    }
  }
}

/** 3 + 4: content check of the verified copy, then the long-lived link. */
async function checkAndSign(
  args: VerifyUploadArgs,
  fetchFn: FetchFn,
  sniffTtl: number,
  verifiedPath: string,
): Promise<VerifyUploadResult> {
  const { bucket, kind } = args;
  const rejected = (reason: string): VerifyUploadResult => ({ ok: false, status: 422, code: "file_rejected", reason });

  const { data: sniffLink, error: sniffErr } = await bucket.createSignedUrl(verifiedPath, sniffTtl);
  if (sniffErr || !sniffLink) {
    if (sniffErr && /not.?found/i.test(sniffErr.message)) return notFound(sniffErr.message);
    return { ok: false, status: 500, code: "internal_error", reason: sniffErr?.message ?? "no sniff link" };
  }

  const head = await readBytes(fetchFn, sniffLink.signedUrl, `bytes=0-${SNIFF_BYTES - 1}`, SNIFF_BYTES);
  if (!head.ok) {
    return head.status === 404
      ? notFound(head.reason)
      : { ok: false, status: 502, code: "internal_error", reason: head.reason };
  }
  const totalSize = totalSizeFromHeaders(head.status, head.headers);

  const check = checkOrcamentoFile({
    kind,
    storedContentType: head.headers.get("content-type"),
    head: head.bytes,
    totalSize,
  });
  if (!check.ok) return rejected(check.reason);

  if (kind === "3mf") {
    if (totalSize === null) return rejected("tamanho do 3MF desconhecido");
    const tail = await readBytes(fetchFn, sniffLink.signedUrl, `bytes=-${ZIP_TAIL_BYTES}`, ZIP_TAIL_BYTES);
    if (!tail.ok) return { ok: false, status: 502, code: "internal_error", reason: `tail: ${tail.reason}` };
    // A server that ignores Range returns the HEAD of the file with 200: only
    // usable when the whole file fits in what was read.
    if (tail.status === 200 && totalSize > tail.bytes.length) {
      return { ok: false, status: 502, code: "internal_error", reason: "range not honoured for the tail" };
    }
    const pkg = await check3mfPackage(tail.bytes, totalSize, async (start, end) => {
      const r = await readBytes(fetchFn, sniffLink.signedUrl, `bytes=${start}-${end}`, end - start + 1);
      return r.ok ? r.bytes : new Uint8Array(0);
    });
    if (!pkg.ok) return rejected(pkg.reason);
  }

  const { data, error } = await bucket.createSignedUrl(verifiedPath, args.linkTtlSeconds);
  if (error || !data) return { ok: false, status: 500, code: "internal_error", reason: error?.message ?? "no data" };
  return { ok: true, verifiedPath, signedUrl: data.signedUrl };
}
