import { describe, it, expect } from "vitest";
import { parse3DFile, type Parsed3DFile } from "@/lib/slicer/3d-file-parser";

describe("3D File Parser (Client-Side .3mf, .gcode, .stl)", () => {
  it("parses Cura .gcode with TIME and Filament weight", async () => {
    const header = ";Generated with Cura 5.4\n;TIME:7200\n;Filament used: 15.2m\n";
    const body = "G28\nG1 Z15.0 F6000\n";
    const footer = ";Filament weight = 45.5\n;End of Gcode\n";
    const content = header + body + footer;
    const file = new File([content], "cube_cura.gcode", { type: "text/plain" });

    const result = await parse3DFile(file);

    expect(result.success).toBe(true);
    expect(result.format).toBe("gcode");
    expect(result.slicer).toBe("Cura");
    expect(result.totalTimeSeconds).toBe(7200);
    expect(result.totalWeightGrams).toBeCloseTo(45.5);
    expect(result.platesCount).toBe(1);
    expect(result.filaments.length).toBeGreaterThanOrEqual(1);
  });

  it("parses Prusa / Bambu / Orca .gcode with estimated printing time and filament used [g]", async () => {
    const header = "; generated by PrusaSlicer 2.7.0\n; estimated printing time (normal mode) = 3h 15m 30s\n";
    const body = "G28 ; home\n";
    const footer = "; filament used [g] = 120.45\n; filament used [mm] = 40320.1\n";
    const content = header + body + footer;
    const file = new File([content], "model_prusa.gcode", { type: "text/plain" });

    const result = await parse3DFile(file);

    expect(result.success).toBe(true);
    expect(result.format).toBe("gcode");
    expect(result.totalTimeSeconds).toBe(3 * 3600 + 15 * 60 + 30); // 11730s
    expect(result.totalWeightGrams).toBeCloseTo(120.45);
    expect(result.platesCount).toBe(1);
  });

  it("detects .stl file and returns educational notice with fallback estimate", async () => {
    const dummyStl = "solid test\nfacet normal 0 0 0\nouter loop\nvertex 0 0 0\nvertex 1 0 0\nvertex 1 1 0\nendloop\nendfacet\nendsolid test\n";
    const file = new File([dummyStl], "bracket.stl", { type: "model/stl" });

    const result = await parse3DFile(file);

    expect(result.format).toBe("stl");
    expect(result.warning).toBeDefined();
    expect(result.warning).toContain("STL");
  });

  it("handles unknown or corrupted files gracefully without crashing", async () => {
    const file = new File(["random garbage text with no slicer tags"], "corrupted.gcode", { type: "text/plain" });

    const result = await parse3DFile(file);

    expect(result.format).toBe("gcode");
    expect(result.slicer).toBe("Unknown");
    expect(result.totalWeightGrams).toBe(0);
    expect(result.totalTimeSeconds).toBe(0);
  });
});
