import { describe, expect, it } from "vitest";
import { buildPixPayload, checkCopiaECola, parseBrCode, sanitizePixText } from "./brcode";

const KEY = "eb2082ad-a521-4ff7-9670-7760988d3126";

/** The real code generated by the bank app for R$ 89,00 (see brcode.test.ts). */
const REAL_8900 =
  "00020126580014br.gov.bcb.pix0136eb2082ad-a521-4ff7-9670-7760988d3126520400005303986540589.005802BR5901N6001C62120508GLTECH3D63044F34";

describe("buildPixPayload", () => {
  it("reproduces the bank-generated code byte for byte", () => {
    expect(
      buildPixPayload({ key: KEY, receiverName: "N", city: "C", amountCents: 8900, txid: "GLTECH3D" }),
    ).toBe(REAL_8900);
  });

  it.each([1, 99, 100, 8900, 12345, 999999, 10_000_000])(
    "round-trips through parseBrCode and checkCopiaECola for %i cents",
    (amountCents) => {
      const code = buildPixPayload({
        key: KEY,
        receiverName: "Guilherme Lanuci",
        city: "Belo Horizonte",
        amountCents,
        txid: "CALC3DPRO",
      });
      const parsed = parseBrCode(code);
      expect(parsed.ok).toBe(true);
      if (!parsed.ok) return;
      expect(parsed.code.amountCents).toBe(amountCents);
      expect(parsed.code.key).toBe(KEY);
      expect(parsed.code.merchantName).toBe("GUILHERME LANUCI");
      expect(parsed.code.merchantCity).toBe("BELO HORIZONTE");
      expect(parsed.code.txid).toBe("CALC3DPRO");
      expect(checkCopiaECola(code, { amountCents, key: KEY }).usable).toBe(true);
    },
  );

  it("omits the amount field when there is no amount", () => {
    const code = buildPixPayload({ key: KEY, receiverName: "N", city: "C", amountCents: null });
    const parsed = parseBrCode(code);
    expect(parsed.ok && parsed.code.amountCents).toBeNull();
    expect(parsed.ok && parsed.code.txid).toBe("***");
  });

  it("sanitizes name, city and txid to what banks accept", () => {
    const code = buildPixPayload({
      key: KEY,
      receiverName: "José da Conceição Calçados Impressão 3D Ltda",
      city: "São João del-Rei do Norte",
      amountCents: 8900,
      txid: "pedido #42/abc",
    });
    const parsed = parseBrCode(code);
    expect(parsed.ok).toBe(true);
    if (!parsed.ok) return;
    expect(parsed.code.merchantName).toBe("JOSE DA CONCEICAO CALCADO");
    expect(parsed.code.merchantName!.length).toBeLessThanOrEqual(25);
    expect(parsed.code.merchantCity!.length).toBeLessThanOrEqual(15);
    expect(parsed.code.merchantCity).toBe("SAO JOAO DEL RE");
    expect(parsed.code.txid).toBe("pedido42abc");
  });

  it("refuses inputs that cannot make a payable code", () => {
    expect(() => buildPixPayload({ key: " ", receiverName: "N", city: "C", amountCents: 1 })).toThrow();
    expect(() => buildPixPayload({ key: KEY, receiverName: "***", city: "C", amountCents: 1 })).toThrow();
    expect(() => buildPixPayload({ key: KEY, receiverName: "N", city: "C", amountCents: -1 })).toThrow();
    expect(() => buildPixPayload({ key: KEY, receiverName: "N", city: "C", amountCents: 1.5 })).toThrow();
  });
});

describe("sanitizePixText", () => {
  it("strips accents, symbols and extra spaces", () => {
    expect(sanitizePixText("  Ação & Cia.  ", 25)).toBe("ACAO CIA");
    expect(sanitizePixText("abcdefghij", 5)).toBe("ABCDE");
  });
});
